service: thedasbot

provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: us-east-1
  profile: thedasbot
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
  resourcePolicy:
    - Effect: Allow
      Principal: '*'
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*
      Condition:
        IpAddress:
          aws:SourceIp:
            - '149.154.160.0/20'
            - '91.108.4.0/22'

functions:
  trigger:
    handler: handler.trigger
    events:
      - http:
          path: thedasbot
          method: post
          cors: true
